// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Testcase1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testcase1() {
    driver.get("http://localhost/ChefBook/home.php");
    driver.manage().window().setSize(new Dimension(790, 864));
    driver.findElement(By.name("select_ingredients")).click();
    driver.findElement(By.cssSelector(".mycheckbox:nth-child(1) > .checkboxmark")).click();
    driver.findElement(By.cssSelector(".mycheckbox:nth-child(23) > .checkboxmark")).click();
    driver.findElement(By.cssSelector(".mycheckbox:nth-child(28) > .checkboxmark")).click();
    driver.findElement(By.name("get_recipe")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) .checkboxmark")).click();
    driver.findElement(By.name("get_instructions")).click();
    driver.findElement(By.name("search")).click();
    driver.findElement(By.name("recipe")).click();
    driver.findElement(By.name("recipe")).sendKeys("Cookie brownies");
    driver.findElement(By.name("get_instructions")).click();
    driver.findElement(By.cssSelector(".mycheckbox:nth-child(3) > input")).click();
    driver.findElement(By.cssSelector(".mycheckbox:nth-child(11) > input")).click();
    driver.findElement(By.name("search_cat")).click();
    driver.findElement(By.cssSelector(".checkboxmark")).click();
    driver.findElement(By.name("get_instructions")).click();
  }
}
